#! /bin/csh -f

#Change to your own paths!
setenv SYSTEM_USERDIR /scratch/eclare

#setenv SRCDIR $HOME/cice.v4.0/cice
setenv SRCDIR /net/bob4/eclare/CODE/CICE_release/CICE.v4.0/cice

setenv CBLD   $SRCDIR/bld
setenv EXEDIR $SYSTEM_USERDIR/rundir4
setenv OBJDIR $EXEDIR/compile

cd $OBJDIR
pwd

# Clean compile directory
gmake -f $CBLD/Makefile clean  || exit 2

cd $EXEDIR

