#! /bin/csh -f

#Change to your own paths!
setenv SYSTEM_USERDIR /scratch/lipscomb

#setenv SRCDIR $HOME/cice.v4.0/cice
setenv SRCDIR /net/bob4/lipscomb/cice40_svn/cice

setenv CBLD   $SRCDIR/bld
setenv EXEDIR $SYSTEM_USERDIR/rundir.v4.0
setenv OBJDIR $EXEDIR/compile

cd $OBJDIR
pwd

# Clean compile directory
gmake -f $CBLD/Makefile clean  || exit 2

cd $EXEDIR

