#! /bin/csh -f

#Change to your own paths!
setenv SYSTEM_USERDIR /scratch2/eclare/CICE.v4.0

#setenv SRCDIR $HOME/cice.v4.0/cice
setenv SRCDIR /usr/projects/climate/eclare/CICE.v4.0/cice

setenv CBLD   $SRCDIR/bld
setenv EXEDIR $SYSTEM_USERDIR/rundir4
setenv OBJDIR $EXEDIR/compile

cd $OBJDIR
pwd

# Clean compile directory
gmake -f $CBLD/Makefile clean  || exit 2

cd $EXEDIR

