#! /bin/csh -f

# SYSTEM_USERDIR is predefined on ORNL machines
setenv SYSTEM_USERDIR /scratch/eclare
#setenv SYSTEM_USERDIR /scratch1/eclare  # epiphany
#setenv SYSTEM_USERDIR /scr/eclare

setenv SRCDIR /net/bob4/eclare/CODE/CICE_release/CICE.v3.14/cice  # mauve
#setenv SRCDIR $HOME/cice.v3.14/cice   

setenv CBLD   $SRCDIR/bld
setenv EXEDIR $SYSTEM_USERDIR/rundir
setenv OBJDIR $EXEDIR/compile

cd $OBJDIR
pwd

# Clean compile directory
gmake -f $CBLD/Makefile clean  || exit 2

cd $EXEDIR

