#! /bin/csh -f

#setenv SYSTEM_USERDIR /pvfs/lipscomb  # ORNL defines this automatically

setenv SRCDIR $HOME/cice.v3.1/cice

setenv CBLD   $SRCDIR/bld
setenv EXEDIR $SYSTEM_USERDIR/rundir
setenv OBJDIR $EXEDIR/compile

cd $OBJDIR
pwd

# Clean compile directory
gmake -f $CBLD/Makefile clean  || exit 2

cd $EXEDIR

