#!/bin/csh
#BSUB -n 8
#BSUB -q schammpq
#BSUB -W 1:00
#BSUB -R "span[hosts=1]"
#BSUB -J cice
#BSUB -N
##BSUB -m n02

set  stamp   = `date -u '+%y%m%d%H%M%S'`
setenv ICE_LOG_FILE       ice.log.${stamp}

echo "Running ice model"

#cice >&! $ICE_LOG_FILE
mpirun -np 8 cice >&! $ICE_LOG_FILE

#
#  Exit
#
rm core*
echo "Exiting job"
exit 0
